import type { Fixture, LeaderboardEntry, OrgSummary } from "@/lib/types";

export const demoOrg: OrgSummary = {
  id: "demo-org",
  name: "Matchday Crew",
  slug: "matchday-crew",
  inviteCode: "KICKOFF26",
  pointsCorrectOutcome: 1,
  pointsExactScore: 3,
};

export const demoFixtures: Fixture[] = [
  {
    id: "demo-1",
    scheduleOrder: 1,
    matchNumber: null,
    stage: "group",
    groupCode: "A",
    kickoffAt: "2026-06-11T19:00:00.000Z",
    kickoffLocalDate: "2026-06-11",
    homeName: "Mexico",
    awayName: "South Africa",
    homeCode: "MEX",
    awayCode: "RSA",
    homeFlag: "🇲🇽",
    awayFlag: "🇿🇦",
    venue: "Mexico City Stadium",
    city: "Mexico City",
    status: "scheduled",
    homeScore: null,
    awayScore: null,
  },
  {
    id: "demo-2",
    scheduleOrder: 2,
    matchNumber: null,
    stage: "group",
    groupCode: "A",
    kickoffAt: "2026-06-12T02:00:00.000Z",
    kickoffLocalDate: "2026-06-11",
    homeName: "Korea Republic",
    awayName: "Czechia",
    homeCode: "KOR",
    awayCode: "CZE",
    homeFlag: "🇰🇷",
    awayFlag: "🇨🇿",
    venue: "Estadio Guadalajara",
    city: "Guadalajara",
    status: "scheduled",
    homeScore: null,
    awayScore: null,
  },
  {
    id: "demo-3",
    scheduleOrder: 3,
    matchNumber: null,
    stage: "group",
    groupCode: "B",
    kickoffAt: "2026-06-12T19:00:00.000Z",
    kickoffLocalDate: "2026-06-12",
    homeName: "Canada",
    awayName: "Bosnia and Herzegovina",
    homeCode: "CAN",
    awayCode: "BIH",
    homeFlag: "🇨🇦",
    awayFlag: "🇧🇦",
    venue: "Toronto Stadium",
    city: "Toronto",
    status: "scheduled",
    homeScore: null,
    awayScore: null,
  },
  {
    id: "demo-4",
    scheduleOrder: 4,
    matchNumber: null,
    stage: "group",
    groupCode: "D",
    kickoffAt: "2026-06-13T01:00:00.000Z",
    kickoffLocalDate: "2026-06-12",
    homeName: "USA",
    awayName: "Paraguay",
    homeCode: "USA",
    awayCode: "PAR",
    homeFlag: "🇺🇸",
    awayFlag: "🇵🇾",
    venue: "Los Angeles Stadium",
    city: "Los Angeles",
    status: "scheduled",
    homeScore: null,
    awayScore: null,
  },
  {
    id: "demo-5",
    scheduleOrder: 7,
    matchNumber: null,
    stage: "group",
    groupCode: "C",
    kickoffAt: "2026-06-13T22:00:00.000Z",
    kickoffLocalDate: "2026-06-13",
    homeName: "Brazil",
    awayName: "Morocco",
    homeCode: "BRA",
    awayCode: "MAR",
    homeFlag: "🇧🇷",
    awayFlag: "🇲🇦",
    venue: "New York New Jersey Stadium",
    city: "New Jersey",
    status: "scheduled",
    homeScore: null,
    awayScore: null,
  },
  {
    id: "demo-6",
    scheduleOrder: 17,
    matchNumber: null,
    stage: "group",
    groupCode: "I",
    kickoffAt: "2026-06-16T19:00:00.000Z",
    kickoffLocalDate: "2026-06-16",
    homeName: "France",
    awayName: "Senegal",
    homeCode: "FRA",
    awayCode: "SEN",
    homeFlag: "🇫🇷",
    awayFlag: "🇸🇳",
    venue: "New York New Jersey Stadium",
    city: "New Jersey",
    status: "scheduled",
    homeScore: null,
    awayScore: null,
  },
  {
    id: "demo-7",
    scheduleOrder: 22,
    matchNumber: null,
    stage: "group",
    groupCode: "L",
    kickoffAt: "2026-06-17T20:00:00.000Z",
    kickoffLocalDate: "2026-06-17",
    homeName: "England",
    awayName: "Croatia",
    homeCode: "ENG",
    awayCode: "CRO",
    homeFlag: "🏴",
    awayFlag: "🇭🇷",
    venue: "Dallas Stadium",
    city: "Dallas",
    status: "scheduled",
    homeScore: null,
    awayScore: null,
  },
  {
    id: "demo-8",
    scheduleOrder: 73,
    matchNumber: 73,
    stage: "round_of_32",
    groupCode: null,
    kickoffAt: null,
    kickoffLocalDate: "2026-06-28",
    homeName: "Group A runners-up",
    awayName: "Group B runners-up",
    homeCode: null,
    awayCode: null,
    homeFlag: "🏆",
    awayFlag: "🏆",
    venue: "Los Angeles Stadium",
    city: "Los Angeles",
    status: "scheduled",
    homeScore: null,
    awayScore: null,
  },
];

export const demoLeaderboard: LeaderboardEntry[] = [
  {
    rank: 1,
    userId: "u1",
    displayName: "Maya",
    avatarUrl: null,
    totalPoints: 18,
    predictionsMade: 8,
    predictionsScored: 7,
    exactScores: 4,
    correctOutcomes: 6,
  },
  {
    rank: 2,
    userId: "u2",
    displayName: "Omar",
    avatarUrl: null,
    totalPoints: 14,
    predictionsMade: 8,
    predictionsScored: 7,
    exactScores: 3,
    correctOutcomes: 5,
  },
  {
    rank: 3,
    userId: "u3",
    displayName: "Numa",
    avatarUrl: null,
    totalPoints: 11,
    predictionsMade: 7,
    predictionsScored: 7,
    exactScores: 2,
    correctOutcomes: 5,
  },
];
